/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ['class'],
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    theme: {
        extend: {
            colors: {
                /* teamcard-sync design tokens — CSS variable driven */
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
                success: {
                    DEFAULT: 'hsl(var(--success))',
                    foreground: 'hsl(var(--success-foreground))',
                },
                warning: {
                    DEFAULT: 'hsl(var(--warning))',
                    foreground: 'hsl(var(--warning-foreground))',
                },
                info: {
                    DEFAULT: 'hsl(var(--info))',
                    foreground: 'hsl(var(--info-foreground))',
                },
                sidebar: {
                    DEFAULT: 'hsl(var(--sidebar-background))',
                    foreground: 'hsl(var(--sidebar-foreground))',
                    primary: 'hsl(var(--sidebar-primary))',
                    'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
                    accent: 'hsl(var(--sidebar-accent))',
                    'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
                    border: 'hsl(var(--sidebar-border))',
                    ring: 'hsl(var(--sidebar-ring))',
                },

                bgLightOrange: '#FFFAF8',
                bgLightPurple: '#FFF6FF',
                bgLime: '#F9FAF6',
                bgIconCard: '#FFF7F6',
                borderPrimaryLight: '#FFE4E4',
                titleText: '#8B8B8B',
                valueText: '#171717',
                iconRed: '#EA3639',
                iconBgRed: '#FFF7F7',
                bgLightYellow: 'rgba(255, 252, 242, 1)',
                bgLightBlue: '#F0FAFF',
                textGreen: '#26A411',
                textGrey: '#9C9DA1',
                textGreyLight: '#828282',
                titleDescription: '#B2B2B2',
                cardHTitleText: '#7b7b7b',
                bgResultCard: ' #F9F9F9',
                impactReportCardBg: '#FAFAFA',
                textRed: '#FF3A3A',
                chatCardBg: '#F9F9F9',
                chatBg: '#FF6A6A',
                contactUsBg: '#FAFAFA',
                faqText: '#4F5D64',
                bgGray: '#F7F9FB',
                textGreenTitle: '#25A311',
                bgSkin: '#FFF6F6',
                bgOrangeShade: '#FFF9F0',
                brandColor: '#FF3A3A',
                bgOrange: '#FF4D4F',
                bgOrange2: '#FF3A3A',
                neutralGray500: '#D9D9D9',
                textBlack: '#000',
                textGray: '#717171',
                textWhitesmoke: '#D1D1D1',
                textDimGray: '#2D2D2D',
                textDimGreen: '#26A411',
                bgDodgerblue: '#1890FF',
                textWhite: '#fff',
                textLime: '#05BE63',
                textMoroon: '#AB1E1E',
                themeSelectorOne: '#FBE7E7',
                themeSelectorTwo: '#22075E',
                themeSelectorThree: '#002766',
                themeSelectorFour: '#A8071A',
                customBorderColor: '#E1E7EE',
                bgLightGray: '#F7F9FB',
                textDarkGray: '#595959',
                bgGrayF8: ' #F8F8F8',
                borderGray: '#E4E7EC',
                bgGrayF9: '#F9F9F9',
                textLightGray: '#7B7B7B',
                bgGrayCard: '#F9F9F9',
                textYellow: '#DEC300',
                textOrange: '#FF910F',
                textGreenLight: '#05BE63',
                textC1B: '#575757',
                bgF7F9Fb: '#F7F9FB',
                bgSoundbox: '#F7F9FB',
                bgLightblue: '#F9F9F9',
                textGreyColor: '#8C8C8C',
                tagColor: '#FFF7F6',
                bgGold: '#FFC700',
                textBtnGray: '#4A4B57',
                skeltonGray: '#F0F0F0',
                listBg: '#f5f5f5',
                textLightGreen: '#72DAA7',
                textDisabledGray: '#808080',
                neutriliseVal: '#1D493E',
                navTextColor: '#212121',
                bgLightGreen: '#E4FFE8',
                bgBluish: '#E6FFF6',
                bgMud: '#F5FFD5',
                textDarkGreen: '#008242',
                textInfoGrey: '#B1B1B1',
                productText: '#A2A2A2',
                bgGreenPayment: '#59CE4E',
                textBlackGray: '#2E2E2E',
                // valueText: '#171717', // Duplicated key, ensure it's intentional or remove/comment out if unnecessary
                bgLightPink: '#FFF4F3',
                bgBlue: '#E3F5FF',
                bgOceanBlue: '#EAFFF7',
                bgOrangeYellow: '#FFF4CD',
                greyBlack: '#F7F7F7',
                signInText: '#424242',
                lightRed: '#FF4F4F',
                limeGray: '#9C9C9C',
                bgDash: '#FFEDED',
                fontBlack: '#0C0C0C',
                fontSubBlack: '#3E3E3E',
                iconSettings: '#1C274C',
                fontHead: '#151515',
                fontSubHeader: '#000000',
                bgSubHeader: '#FFE8E8',
                bgPalePink: '#FFF8F6',
                salaryText: '#404040',
                salarySubText: '#9E9E9E',
                salaryTableHead: '#FAFBFB',
                salaryTableText: '#42526D',
                salaryTableSubText: '#0A0A0A',
                salaryTableButton: '#3DC926',
                textUpcoming: '#DAAA01',
                esimInfoCardYellow: '#FFFEDB',
                esimInfoCardPink: '#FFF3F3',
                esimInfoCardPurple: '#FCF9FF',
                accountingDashboardText: '#818181',
                highLightBlue: '#00dfff',
                lightGreen: '#EFFFE8',
                magnolia: '#F9F4FF',
                seashell: '#FFF6F2',
                cornsilk: '#FFFBE4',
                lumyBlack: '#2B2B2B',
                headBlack: '#333333',
                limeGreen: '#F6FFED',
                footGrey: '#757575',
                successGreen: '#43AA00',
                stageGrey: '#666666',
                linkBlue: '#3b82f6',
                borderBlack: '#100c08',
                lightBlack: '#333333',
                newBlack: '#4C4C4C',
                paymentGreen: '#46BE0F',
                vidoCallGreen: '#03B94D',
                audioCallGreen: '#38D58A',
                declineCallRed: '#FF0000',
            },
            fontSize: {
                custom: '15px',
                lightGray: '#C7C7C7',
            },
            screens: {
                // to match with antD screen sizes
                xs: '0px', // >=0
                sm: '576px', // >=576
                md: '768px', // >=768
                lg: '992px', // >=992
                xl: '1200px', // >=1200
                xxl: '1600px', // >=1600
            },
            fontWeight: {
                'extra-light': 300,
                regular: 400,
                'extra-bold': 800,
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
            keyframes: {
                'accordion-down': {
                    from: { height: '0' },
                    to: { height: 'var(--radix-accordion-content-height)' },
                },
                'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to: { height: '0' },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
            },
        },
        fontFamily: {
            helvetica: ['Helvetica', 'Arial', 'sans-serif'],
            roboto: ['Roboto', 'sans-serif'],
        },
    },
    plugins: [require('tailwindcss-animate')],
};
