// ------------------------------------------------------------------------

const ROOTS = {
    AUTH: '/auth',
    ADMIN: '/admin',
    ECOM: '/manager',
    SYSYTEM_USER: '/system-user',
};

// ------------------------------------------------------------------------

export const paths = {
    // AUTH
    auth: {
        jwt: {
            login: `${ROOTS.AUTH}/login`,
            register: `${ROOTS.AUTH}/register`,
        },
        resetPassword: `/reset-password`,
        setPassword: `/set-password`,
        passwordSuccess: '/password-update-success',
    },
    // DASHBOARD
    dashboard: {
        home: '/dashboard',
        billPayments: '/bill-payments',
        corporateTravel: '/corporate-travel',
        payroll: '/payroll',
        officeSupplies: '/office-supplies',
        subscriptions: '/softwares',
        logistics: '/logistics',
        giftCards: '/gift-cards',
        connect: '/marketplace',
        works: '/more-services/works',
        invoicing: '/collector',
        zeroCarbon: '/more-services/zero-carbon',
        tax: '/tax',
        accounting: '/accounting',
        moreServices: '/more-services',
        reports: '/reports',
        needHelp: '/need-help',
        profile: '/profile',
        bussinessDocs: '/more-services/business-docs',
        documentAttestation: '/more-services/document-attestation',
        whatsappForBusiness: 'more-services/whatsapp',
        eSign: 'more-services/eSign',
        esr: 'accounting/ESR',
        vendorPayouts: 'more-services/vendorPayouts',
        licenseRenewal: '/more-services/license-renewal',
        officeAddress: '/more-services/office-address',
        hotels: '/hotels',
        paymentLink: '/payment-links',
        perks: '/perks',
        notifications: '/notifications',
        payments: '/payments',
        pekoClub: '/peko-club',
        pekoCloud: '/peko-cloud',
        corporateCard: '/corporate-cards',
        insurance: '/insurance',
        settings: '/settings',
        plans: '/plans',
        serviceNotAvailable: '/service-not-available',
        pekoConnect: '/more-services/peko-connect',
        hike: '/more-services/hike',
        emailDomain: '/more-services/email-domain',
        einvoicing: '/einvoicing',
        eosb: '/eosb',
        ruyaSupport: '/more-services/ruya-support',
        bankAccount: '/more-services/bank-account',
        oneKYB: '/more-services/one-kyb',
        businessListings: '/more-services/business-listings',
    },
    payments: {
        index: 'payments',
        paymentsuccess: 'payment-success',
        paymentFailure: 'payment-failure',
    },
    home: {
        index: 'dashboard',
        plans: 'plans',
    },
    billPayments: {
        index: 'bill-payments',
        duPrepaid: 'du-prepaid',
        duPostpaid: 'du-postpaid',
        bulkUpload: 'bulkupload',
        bulkPayment: 'bulkPayment',
        etisalatPrepaid: 'etisalat-prepaid',
        etisalatPostpaid: 'etisalat-postpaid',
        AADC: 'AADC',
        ADDC: 'ADDC',
        ajmanSewerage: 'ajman-sewerage',
        EWE: 'EWE',
        lootah: 'lootah-gas',
        NOL: 'nol',
        salik: 'salik',
        sewa: 'sewa',
        dubaiPolice: 'dubai-police',
        dubaiPoliceTicket: 'tickets',
        darb: 'DARB',
        hafilat: 'hafilat',
        hafilatDetails: 'hafilat-details',
    },
    zeroCarbon: {
        id: '/:id',
        index: 'zero-carbon',
        carbonCalculator: 'carbon-calculator',
        result: 'result',
        projectDetails: 'project-details',
        neutralize: 'neutralize',
        buyCredits: 'buy-Credits',
        impactReport: 'impact-report',
        projectListing: 'project-listing',
        whyAct: 'why-act',
        transactions: 'transactions',
        payment: 'payment',
        paymentStatus: 'payment-status',
        shareImpact: 'share-impact',
    },
    connect: {
        index: 'marketplace',
        details: 'details/:id',
        success: 'success',
        failed: 'failed',
    },
    needHelp: {
        index: 'need-help',
        faq: 'frequently-asked-questions',
    },
    paymentLinks: {
        index: 'payment-links',
        CreatePayment: 'create',
    },
    payroll: {
        index: 'payroll',
        announcements: 'announcements',
        id: '/:id',
        eId: '/:eId',
        salaryProfile: 'salary-profile',
        addEmployee: 'add-employee',
        employeesSalary: 'employees-salary',
        employeeProfile: 'employee-profile',
        processSalary: 'process-salary',
        employees: 'employees',
        hrSettings: 'HR-settings',
        activityCalendar: 'activity-calendar',
        bulkUpload: 'bulk-upload',
        employeeLeave: 'employee-Leaves',
        wpsRegistration: 'wps-registration',
        employeeSuccess: 'success',
        documentsAndAssets: 'employee-documents',
        employeeReimbursement: 'employee-reimbursements',
    },
    pekoCloud: {
        index: 'peko-cloud',
        settings: 'settings',
        taskToDo: 'task-to-do',
        companyDocuments: 'company-documents',
        ownershipDocuments: 'ownership-documents',
        financials: 'financials',
        employeeDetails: 'employee-details',
        subscriptions: 'subscriptions',
        assets: 'assets',
        assetsDetails: 'assets-details',
        fleet: 'fleet',
        fleetDetails: 'fleet-details',
        chequeBookDetails: 'cheque-book-details',
        chequeDetails: 'cheque-details',
    },
    accounting: {
        index: 'accounting',
        accountsDashboard: 'accounts-dashboard',
        vatRegistration: 'vat-registration',
        businessHealthCheck: 'business-health-check',
        taxRegistration: 'corporate-tax-registration',
        vatSuccess: 'vat-success',
        taxSuccess: 'tax-success',
        TaxRegisterReview: 'tax-review',
        TaxHistory: 'tax-history',
        TaxOrderDetails: 'tax-order-details',
    },
    businessDocs: {
        index: 'business-docs',
        category: 'category',
    },
    logistics: {
        index: 'logistics',
        details: 'shipment-details',
        payment: 'payment',
        paymentStatus: 'payment-status',
        track: 'track',
        orderHistory: 'order-history',
        orderDetails: 'order-view',
    },
    licenseRenewal: {
        index: 'license-renewal',
        details: 'voucher-details',
    },
    subscriptions: {
        index: 'softwares',
        id: '/:id',
        details: 'details',
        companyDetails: 'purchase',
        payment: 'payment',
        success: 'success',
        failed: 'failed',
        orderHistory: 'order-history',
    },
    officeSupplies: {
        index: 'office-supplies',
        id: 'id',
        productDetails: 'product-details',
        cartPage: 'cart',
        orderPlaced: 'order-placed',
        orderDetails: 'order-details',
        orderHistory: 'order-history',
    },
    invoice: {
        index: 'collector',
        kybPage: 'KYB',
        kybDocumentPage: 'documents',
        kybSuccess: 'kyb-success',
        upload: 'upload-invoice',
        create: 'create-invoice',
        customers: 'customers',
        invoicedetails: 'invoice-details',
        invoicehistory: 'track-invoice',
        trackDetails: 'invoice-history-details',
        guidelines: 'guidelines',
        success: 'success',
        paymentLinks: 'payment-links',
        orderHistory: 'order-history',
    },
    giftcards: {
        index: 'gift-cards',
        details: 'details',
        id: '/:id',
        orderHistory: 'order-history',
        checkout: 'checkout',
        success: 'success',
        failure: 'failure',
    },
    hotels: {
        index: 'hotels',
        details: 'hotel-listing',
        hotelView: 'hotel-details',
        bookings: 'booking-summary',
        manageBookings: 'manage-bookings',
        userDetails: 'guest-information',
        reviewPayment: 'payment-review',
    },
    airline: {
        index: 'airline',
        results: 'flight-details',
        details: 'passenger-details',
        manage: 'manage',
        bookingDetails: 'booking',
        cancelDetails: 'cancel',
        cancelSuccess: 'success',
        modify: 'modify',
    },
    officeAddress: {
        index: 'office-address',
        plans: 'plans',
        basic: 'basic',
        premium: 'premium',
        flexi: 'flexi',
        orderhistory: 'order-history',
    },
    documentAttestation: {
        index: 'document-attestation',
        orderdetails: 'order-details',
        orderhistory: 'order-history',
        deliveryDetails: 'delivery-details',
    },
    whatsappForBusiness: {
        index: 'whatsapp',
        MyProjects: 'my-projects',
        orderhistory: 'order-history',
        paymentsuccess: 'payment-success',
    },
    pekoClub: {
        index: 'peko-club',
        events: 'events',
        news: 'news',
        newsDetails: 'news-details',
        eventDetails: 'event-details',
    },
    works: {
        index: 'works',
        detail: 'details',
        id: ':id',
        purchased: 'purchased',
        purchase: 'purchase',
        planId: ':planId',
        orderHistory: 'order-history',
        orderDetails: 'order-details',
    },
    esim: {
        index: 'eSIM',
        packages: 'packages',
        details: 'package-details',
        orders: 'orders',
        esimDetails: 'package-details',
        ReplacePackage: 'replace-package',
        topup: 'top-up-package-details',
        howEsim: 'how-it-works',
    },
    eSign: {
        index: 'eSign',
        uploadPage: 'upload',
        viewPage: 'view',
        historyPage: 'status',
        successPage: 'success',
        settings: 'settings',
    },
    hike: {
        index: 'hike',
        purchasePage: 'purchase-hike',
        checkoutPage: 'purchase-details',
        historyPage: 'history',
        successPage: 'success',
    },
    emailDomain: {
        index: 'email-domain',
        detailsPage: 'detail',
        historyPage: 'order-history',
    },
    esr: {
        index: 'ESR',
        stage1: 'stage1',
        stage2: 'stage2',
        view: 'view',
        stageView: 'stage-view',
        stage3: 'stage3',
        registrationAssessment: 'stages',
        registrationNotification: 'registration-notification',
        payment: 'payment',
        paymentSuccess: 'payment-success',
        paymentFailure: 'payment-failure',
        stageSuccess: 'stage-success',
        orderHistory: 'order-history',
        orderHistoryDetails: 'order-history-details',
        id: ':id',
    },
    vendorPayouts: {
        index: 'vendorPayouts',
        upload: 'upload-invoice',
        beneficiaryReceives: 'beneficiary-receives',
        beneficiary: 'beneficiary',
        registerBeneficiary: 'beneficiary-register',
        estimateCalculator: 'estimate-calculator',
        activateAccount: 'activate-account',
    },

    pekoConnect: {
        index: 'peko-connect',
    },

    insurance: {
        index: 'insurance',
        orders: 'orders',
        insurance: 'Policybazaar',
    },
    settings: {
        index: 'settings',
    },
    plans: {
        index: 'plans',
        reviewOrder: 'review-order',
        paymentsuccess: 'payment-success',
        paymentFailure: 'payment-failure',
    },
    eosb: {
        index: 'eosb',
    },
    einvoicing: {
        index: 'einvoicing',
        activate: 'activate',
        eligibility: 'eligibility',
        onboarding: 'onboarding',
        salesInvoices: 'sales-invoices',
        creditNotes: 'credit-notes',
        purchaseInvoices: 'purchase-invoices',
        purchaseCreditNotes: 'purchase-credit-notes',
        new: 'new',
        bulkUpload: 'bulk-upload',
        archive: 'archive',
        settingsProfile: 'settings/profile',
        settingsApi: 'settings/api',
        settingsBranches: 'settings/branches',
    },
    admin: {
        index: `${ROOTS.ADMIN}`,
        dashboard: `${ROOTS.ADMIN}/dashboard`,
        users: `${ROOTS.ADMIN}/users`,
        accounts: `${ROOTS.ADMIN}/accounts`,
        reports: `${ROOTS.ADMIN}/reports`,
        officeSupplies: `${ROOTS.ADMIN}/office-supplies`,
        support: `${ROOTS.ADMIN}/support`,
        manage: `${ROOTS.ADMIN}/manage`,
        bulkUpload: `${ROOTS.ADMIN}/bulk-upload`,
        settings: `${ROOTS.ADMIN}/settings`,
        needHelp: `${ROOTS.ADMIN}/need-help`,
        announcement: `${ROOTS.ADMIN}/announcements`,
    } as Record<string, string>,
    ecomManager: {
        index: `${ROOTS.ECOM}`,
        dashboard: `${ROOTS.ECOM}/dashboard`,
        orders: `${ROOTS.ECOM}orders`,
        needHelp: `${ROOTS.ECOM}/need-help`,
        officeSupplies: `${ROOTS.ECOM}/officeSupplies`,
        returnAndRefunds: `${ROOTS.ECOM}/returnAndRefunds`,
        cancelAndRefunds: `${ROOTS.ECOM}/cancelAndRefunds`,
        vendors: `${ROOTS.ECOM}/vendors`,
        categories: `${ROOTS.ECOM}/categories`,
        products: `${ROOTS.ECOM}/products`,
    } as Record<string, string>,
    systemUser: {
        profile: `${ROOTS.SYSYTEM_USER}/profile`,
        index: `${ROOTS.SYSYTEM_USER}`,
        dashboard: `${ROOTS.SYSYTEM_USER}/dashboard`,
        users: `${ROOTS.SYSYTEM_USER}/users`,
        accounts: `${ROOTS.SYSYTEM_USER}/accounts`,
        reports: `${ROOTS.SYSYTEM_USER}/reports`,
        officeSupplies: `${ROOTS.SYSYTEM_USER}/office-supplies`,
        support: `${ROOTS.SYSYTEM_USER}/support`,
        manage: `${ROOTS.SYSYTEM_USER}/manage`,
        bulkUpload: `${ROOTS.SYSYTEM_USER}/bulk-upload`,
        settings: `${ROOTS.SYSYTEM_USER}/settings`,
        systemConfiguration: `${ROOTS.SYSYTEM_USER}/system-configuration`,
        needHelp: `${ROOTS.SYSYTEM_USER}/need-help`,
        announcement: `${ROOTS.SYSYTEM_USER}/announcements`,
        paymentLinks: `${ROOTS.SYSYTEM_USER}/payment-links`,
        esrView: `${ROOTS.SYSYTEM_USER}/manage/esr-view`,
    } as Record<string, string>,
};
