import React from 'react';

import { InboxOutlined } from '@ant-design/icons';
import type { UploadProps } from 'antd';
import { Button, Flex, message, Typography, Upload } from 'antd';

const { Dragger } = Upload;
const props: UploadProps = {
    name: 'file',
    multiple: false,
    maxCount: 1,
    action: 'https://run.mocky.io/v3/435e224c-44fb-4773-9faf-380c5e6a2188',
    onChange(info) {
        const { status } = info.file;
        if (status !== 'uploading') {
            // console.log(info.file, info.fileList);
        }
        if (status === 'done') {
            message.success(`${info.file.name} file uploaded successfully.`);
        } else if (status === 'error') {
            message.error(`${info.file.name} file upload failed.`);
        }
    },
    onDrop(e) {
        // console.log('Dropped files', e.dataTransfer.files);
    },
};

const UploadBankStatement = () => (
    <Flex justify="center" className="py-3">
        <Flex vertical gap={20} align="center" justify="center" className="w-3/4">
            <Dragger {...props} className="bg-white w-100">
                <Flex vertical className="mx-5">
                    <p className="ant-upload-drag-icon text-black">
                        <InboxOutlined />
                    </p>
                    <Typography.Text>Click or drag .CSVfile to this area to upload</Typography.Text>
                    <Typography.Text className="text-green-500">
                        Note: Upload the bank statement is csv format, this can be generated by log
                        in to corporate bank account
                    </Typography.Text>
                </Flex>
            </Dragger>
            <Button type="primary" danger className="w-full">
                Submit
            </Button>
        </Flex>
    </Flex>
);

export default UploadBankStatement;
